"use strict";

const uploadBtn = document.getElementById("uploadBtn");
const data = document.getElementsByClassName("blog-data");
const publishedBtn = document.getElementById("publishedBtn");
const publisedMsg = document.getElementById("publishedMsg");
const thumnailSelect = document.getElementById("thumnailSelect");
const thumnailPath = document.getElementById("thumnailPath");
const thumnailSeo = document.getElementById("thumnailSeo");
const thumnail = document.getElementById("thumnail");
const addBtnCate = document.getElementById("addBtnCate");
const addBtnTag = document.getElementById("addBtnTag");
const addBtnImg = document.getElementById("addBtnImg");
const tagOkBtn = document.getElementById("tagOkBtn");
const tagInputBox = document.getElementById("tagInputBox");
const summaryInputBtn = document.getElementById("summaryInputBtn");
const body = document.getElementById("body");
const summary = document.getElementById("summary");
const summaryCount = document.getElementById("summaryCount");
const preview = document.getElementById("preview");
const previewBtn = document.getElementById("previewBtn");
const bodyWrapper = document.getElementById("bodyWrapper");
let isPreview = false;
const ctl_table = document.getElementById("ctl_table");
const ctl_img = document.getElementById("ctl_img");
const ctl_img_select = document.getElementById("ctl_img_select");
